prefix = "!"
color = 0x202225

[help]
    no_commands = "*No commands*"
    [help.bot]
        title = "Help menu"
        description = "Use `{} [command]` for more info on a command.\nYou can also use `{} [category]` for more info on a category."